### ISSUE TITLE
Help to install on vencord

### ISSUE THREAD

**Issue by Soulivan71** [ethan-davies/ToastNotificationsMerge#1]
Hello can u help me with installation plz ?

**Comment by ethan-davies** [comment]
Of course, here is a link to a video that should solve all of your issues:

https://youtu.be/8wexjSo8fNw?si=-MP80HosqJAuyANA

If you need any further help from that video then feel free to ask me (try to keep the problem as detailed as possible so I can get a better grasp of the situation)

**Comment by Soulivan71** [comment]
Im having issue 
![image](https://github.com/ethan-davies/ToastNotificationsMerge/assets/36502190/4ec3c2d4-327d-476b-bd34-9ed1c0089924)
(Im in vertical thats maybe the pb)

**Comment by ethan-davies** [comment]
That is most likely the reason. I can improve the CSS in a future push

**Comment by Soulivan71** [comment]
Thx u, 
Like Im using discord in my snd screen, I have the notification always display (and timebar doesn't load)
![image](https://github.com/ethan-davies/ToastNotificationsMerge/assets/36502190/d153040a-2c52-4831-8c5e-3a252ea3b36a)
This ^^ keep stuck like (isn't focus even if it is)

**Comment by ethan-davies** [comment]
In regards to that we don’t modify that part of the CSS. That would be an issue that would have to be changed in the Vencords CSS and not the one in our plugins

**Comment by Soulivan71** [comment]
Hmm so I need to wait update from vencord ? 🤔

**Comment by ethan-davies** [comment]
> Hmm so I need to wait update from vencord ? 🤔 

Yes.
