### ISSUE TITLE
plugin is broken 

### ISSUE THREAD

**Issue by realonyx** [ethan-davies/ToastNotificationsMerge#4]
the plugin is not working , is not showing messages, maybe because latest discord update. I hope you guys fix it its really important plugin. thanks

**Comment by Mousica-dev** [comment]
made a pr a fix, until they merge it you can js use the pr

**Comment by ethan-davies** [comment]
Issue should now be fixed in the new merge (https://github.com/ethan-davies/ToastNotificationsMerge/pull/5)
